[package]
name = "minecraft-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = "0.55.0"
gl = "0.14.0"
image = "0.24.5"
rand = "0.8.5"
